"""
Decode a QR PNG generated by export_day_to_qr back to the original JSON envelope.

Usage:
    python scripts/decode_qr.py data/qrcodes/day_2026-04-16T10-00-00Z.png

Requires: apt install libzbar0 && pip install pyzbar pillow
"""

import base64
import gzip
import json
import sys
from pathlib import Path


def main():
    if len(sys.argv) != 2:
        print("Usage: python scripts/decode_qr.py <path/to/day_*.png>")
        sys.exit(1)

    png = Path(sys.argv[1])
    if not png.exists():
        print(f"File not found: {png}")
        sys.exit(1)

    try:
        from PIL import Image
        from pyzbar.pyzbar import decode as pyzbar_decode
    except ImportError:
        print("Missing deps. Run: sudo apt install libzbar0 && pip install pyzbar pillow")
        sys.exit(1)

    results = pyzbar_decode(Image.open(str(png)))
    if not results:
        print("No QR code found in image.")
        sys.exit(1)

    raw = results[0].data.decode("ascii")

    # Try plain JSON first (fallback reference path)
    try:
        obj = json.loads(raw)
        print("QR type: reference (payload too large, full data in JSON file)")
        print(json.dumps(obj, indent=2))
        return
    except json.JSONDecodeError:
        pass

    # Standard path: base64 → gzip → JSON
    envelope = json.loads(gzip.decompress(base64.b64decode(raw)))
    print("QR type: full data")
    print(json.dumps(envelope, indent=2))


if __name__ == "__main__":
    main()
